/* Generated by Edge Impulse
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 1, 2, 3 };

// (before - mean) / scale
const float ei_classifier_anom_scale[4] = { 0.2470567867912088, 0.24698064036781692, 0.2472303976094343, 0.24705627798714916 };
const float ei_classifier_anom_mean[4] = { 0.6889391673890792, 0.6866095058781945, 0.6911714221264079, 0.6889538454030704 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[6] = {
	{ ( float[4] ) { -1.629145622253418, -1.6231571435928345, -1.6343251466751099, -1.6292071342468262 }, 0.16719535642103664 },
	{ ( float[4] ) { -0.15046648681163788, -0.16886544227600098, -0.1306605041027069, -0.15014901757240295 }, 0.904480574900246 },
	{ ( float[4] ) { 0.5439049005508423, 0.540903627872467, 0.5466591715812683, 0.5439046025276184 }, 0.6881756952187605 },
	{ ( float[4] ) { 1.018302083015442, 1.021917700767517, 1.0139374732971191, 1.0182545185089111 }, 0.5019336895261963 },
	{ ( float[4] ) { -0.7258263230323792, -0.7286490201950073, -0.7226352691650391, -0.7258117198944092 }, 0.5743451151146309 },
	{ ( float[4] ) { -1.2019239664077759, -1.1972177028656006, -1.20577871799469, -1.2019753456115723 }, 0.49600782816360633 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
